// web/src/routes/dash/+page.svelte
<script lang="ts">
	import { type User, AuthStore } from "@lib/auth";
	import { type Sort, fetchRepos } from "./requests";
	import Spinner from "@components/spinner.svelte";
	import Repo from "./components/Repo.svelte";
	import { onMount } from "svelte";
	import { refresh } from "../auth";
	import type { Repository } from "./types";

	// sort
	const SortDefault: Sort = "pushed";
	const sortFunctions: Record<string, Sort> = {
		Created: "created",
		Pushed: "pushed",
		Updated: "updated",
		Name: "full_name",
	};

	// page limit
	const ShowDefault: string = "30";

	let user: User | undefined;
	let page: number = 0;
  function handlePage(i: number): (e: Event) => void {
    return async (e: Event) => {
      e.preventDefault();
      if (page === 0 && i === -1) return;
      page += i;
      await getRepos()
    }
  }

	let show: string = ShowDefault;
  async function handleShow(e: Event) {
    e.preventDefault();
    show = (e.target as HTMLSelectElement)?.value;
    await getRepos();
  }


	let sort: Sort = SortDefault;
  async function handleSort(e: Event) {
    e.preventDefault();
    sort = (e.target as HTMLSelectElement)?.value as Sort;
    await getRepos();
  }

  let repos: Array<Repository> = [];
  let loading: boolean = true;
  let error: string | undefined;
	onMount(async () => {
		user = AuthStore.user();
    if (!user) {
      AuthStore.refreshSession();
      return
    }
    await getRepos();
	});

  async function handleRefetch(e: Event) {
    e.preventDefault();
    await getRepos();
  }

  async function getRepos() {
    try {
      loading = true;
      repos = await fetchRepos(page, sort, show)
    } catch (e) {
      error = (e as Error).message;
    } finally {
      loading = false;
    }
  }


	let search: string = "";
  function handleSearch(e: Event) {
    search = (e.target as HTMLInputElement)?.value ?? "";
  }

</script>

<main class="px-4 md:px-10">
	<section class="mt-5 px-4">
		<div class="flex flex-col items-center justify-center gap-2 md:w-max">
			<img
				alt="hn275"
				role="presentation"
				src={user?.avatar_url}
				class="w-20 rounded-full"
			/>
			<div>
				<h2 class="inline-block text-lg font-semibold">{user?.name}</h2>
				&nbsp;
				<span class="text-xs">({user?.login})</span>
			</div>
		</div>
	</section>

	<section class="p-5 md:p-7 mt-12 bg-dark-100 rounded-lg">
		<h1 class="text-gradient text-2xl font-semibold mb-3">Repositories</h1>

		<div class="">
			<div class="grid grid-cols-2">

				<div>
					<label for="sort">Sort by: </label>
					<select name="sort" class="" on:change={handleSort}>
						{#each Object.entries(sortFunctions) as [name, s]}
							<option value={s} selected={sort === s}>
								{name}
							</option>
						{/each}
					</select>
				</div>

				<div>
					<label for="show">Show:</label>
					<select name="show" class="" on:change={handleShow}>
						{#each ["10", "20", "30"] as i}
							<option selected={i === show}>
								{i}
							</option>
						{/each}
					</select>
				</div>
			</div>

			<div class="flex flex-col">
				<label for="repo-search">Search bar</label>
        <input name="repo-search" on:input={handleSearch}/>
			</div>
		</div>

		<hr class="text-main border-main my-6 rounded-lg border" />

    {#if error}
      <div class="p-5 bg-red-400 rounded-lg text-dark-200">
        <h2 class="font-bold text-lg inline">Whoops!</h2>
        <span>An error has occured:</span>
        <p>{error}</p>
      </div>

    {:else if loading}
      <div
        class="flex h-64 w-full flex-col items-center justify-center gap-3"
      >
        <Spinner class="stroke-main" />
        <p>Fetching data...</p>
      </div>

    {:else}
      {#if repos.length === 0}
        <p>You don't have any repository yet.</p>

      {:else}
        <ul class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {#each repos.filter((d) => d.full_name.includes(search ?? "")) as repo (repo.id)}
            <Repo {repo} />
          {/each}

        </ul>

        <div class="">
          <button on:click={handlePage(-1)}>prev</button>
          <p>{page}</p>
          <button on:click={handlePage(1)}>next</button>
        </div>

      {/if}

    {/if}
  </section>
</main>

// web/src/pages/dash/Dash.tsx
import { useEffect, useState, ChangeEvent } from "react";
import { Repository } from "./types";
import { Repo } from "./Repo";
import { useAuth } from "context/auth";
import { makeUrl } from "lib/url";
import { Layout } from "components/Layout";
import { Spinner } from "components/Spinner";

// sort
type Sort = "created" | "updated" | "pushed" | "full_name";
const SortDefault: Sort = "pushed";
const sortFunctions: Record<string, Sort> = {
  Created: "created",
  Pushed: "pushed",
  Updated: "updated",
  Name: "full_name",
};
// page limit
const ShowDefault: number = 30;

export function Dash() {
  const {
    data,
    loading,
    handlePrevPage,
    handleNextPage,
    error,
    page,
    handleSort,
    handleShow,
    search,
    handleSearch,
  } = useRepos();

  const {
    state: { user },
  } = useAuth();

  return (
    <Layout className="px-4 md:px-10">
      <section className="mt-5 px-4">
        <div className="flex flex-col items-center justify-center gap-2 md:w-max">
          <img src={user?.avatar_url} className="w-20 rounded-full" />
          <div>
            <h2 className="inline-block text-lg font-semibold">{user?.name}</h2>&nbsp;
            <span className="text-xs">({user?.login})</span>
          </div>
        </div>
      </section>

      <section className="">
        <h1 className="text-gradient text-2xl font-semibold">Repositories</h1>

        <div className="">
          <div className="grid grid-cols-2">
            <div>
              <label htmlFor="sort">Sort by: </label>
              <select
                name="sort"
                className=""
                onChange={handleSort}
                defaultValue={SortDefault}
              >
                {Object.entries(sortFunctions).map(([name, sort]) => (
                  <option key={sort} value={sort}>
                    {name}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label htmlFor="show">Show: </label>
              <select
                name="show"
                className=""
                onChange={handleShow}
                defaultValue={ShowDefault}
              >
                {[10, 20, 30].map((i) => (
                  <option key={i} value={i}>
                    {i}
                  </option>
                ))}
              </select>
            </div>
          </div>

          <div className="flex flex-col">
            <label htmlFor="repo-search">Search bar</label>
            <input name="repo-search" value={search} onChange={handleSearch} />
          </div>
        </div>


        <hr className="text-main border-main my-4 rounded-lg border" />


        {loading ? (
          <div className="flex h-64 w-full flex-col items-center justify-center gap-3">
            <Spinner className="stroke-main" />
            <p>Fetching data...</p>
          </div>
        ) : error ? (
          <p>{error}</p>
        ) : (
          <>
            {data.length === 0 ? (
              <p>You don't have any repository yet.</p>
            ) : (
              <>
                <ul className="mt-2 flex flex-col gap-3">
                  {data
                    .filter((d) => d.full_name.includes(search ?? ""))
                    .map((repo) => (
                      <Repo key={repo.id} {...repo} />
                    ))}
                </ul>
                <div className="">
                  <button onClick={handlePrevPage}>prev</button>
                  <p>{page}</p>
                  <button onClick={handleNextPage}>next</button>
                </div>
              </>
            )}
          </>
        )}
      </section>

    </Layout>
  );
}

/* HOOKS */
function useRepos() {
  const { getToken, dispatch } = useAuth();
  // HANDLE QUERIES
  const [page, setPage] = useState<number>(1);
  const [sort, setSort] = useState<Sort>(SortDefault);
  const [show, setShow] = useState<number>(ShowDefault);
  const [data, setData] = useState<Repository[]>([]);
  const [error, setError] = useState<string>();
  const [loading, setLoading] = useState<boolean>(true);
  useEffect(() => {
    const tok = getToken();
    if (!tok) {
      dispatch({ type: "logout" });
      return;
    }

    const url = makeUrl("/repos", { page, sort, show });

    const headers = new Headers({
      Accept: "application/json",
      Authorization: `Bearer ${tok}`,
    });
    (async () => {
      try {
        setLoading(() => true);
        const response = await fetch(url, {
          method: "GET",
          headers,
          credentials: "include",
        });
        const { status } = response;

        if (status === 401 || status === 403) {
          dispatch({ type: "logout" });
          return;
        }

        const payload = await response.json();
        if (status === 200) setData(() => payload as Repository[]);
        else setError(() => payload["message"]);
      } catch (e) {
        setError(() => "Server is not responding, try again later.");
        console.error(e);
      } finally {
        setLoading(() => false);
      }
    })();
  }, [page, show, sort]);

  function handleNextPage() {
    const len = data?.length ?? 0;
    if (len < show) return;
    setPage((p) => p + 1);
  }

  function handlePrevPage() {
    if (page <= show) {
      setPage(() => 1);
      return;
    }
    setPage((p) => p - 1);
  }

  function handleSort(e: ChangeEvent<HTMLSelectElement>) {
    setSort(() => e.target.value as Sort);
  }

  function handleShow(e: ChangeEvent<HTMLSelectElement>) {
    setShow(() => Number(e.target.value as Sort));
  }

  // HANDLE SEARCH
  const [search, setSearch] = useState<string>();
  function handleSearch(e: ChangeEvent<HTMLInputElement>) {
    setSearch(() => e.target.value);
  }

  return {
    data,
    error,
    handleNextPage,
    handlePrevPage,
    page,
    loading,
    show,
    handleSort,
    handleShow,
    search,
    handleSearch,
  };
}
