// web/src/pages/home/Nav.tsx
import { useState } from "react";
import Logo from "assets/logo.svg";
import cx from "classnames";
import { MdMenu } from "react-icons/md";
import { BsChevronCompactUp } from "react-icons/bs";
import { AiFillGithub, AiFillStar } from "react-icons/ai";

interface Props {
	oauthUrl: string;
	githubUrl: string;
}
export function Nav({ oauthUrl, githubUrl }: Props) {
	const { open, toggleOpen } = useMenu();

	return (
		<nav className="justify-between md:flex md:backdrop-blur">
			<div className="flex h-16 items-center justify-between px-5">
				<img src={Logo} alt="logo" />
				<button
					onClick={toggleOpen}
					className="rounded-md bg-inherit p-2 transition-all hover:bg-[#3a3a3a] md:hidden"
				>
					<MdMenu className="text-xl text-main" />
				</button>
			</div>

			<div
				className={cx(["absolute left-0 top-16 w-full", "md:static md:w-max"])}
			>
				<ul
					className={cx([
						`w-full ${open ? "h-[350px] py-5" : "h-0 py-0"}`,
						"bg-[#1e1e1e] font-semibold text-light",
						"flex flex-col items-center justify-between",
						"transition-all",
						"relative overflow-clip",
						"z-50 gap-10 md:h-full md:flex-row md:bg-inherit",
					])}
				>
					<li>
						<a
							href={oauthUrl}
							className={cx([
								"flex items-center hover:cursor-pointer hover:no-underline",
								"text-main md:rounded-md md:bg-main md:px-3 md:py-2 md:text-dark",
								"transition-all hover:brightness-95",
							])}
						>
							<span>
								<AiFillGithub />
							</span>
							&nbsp; Sign in
						</a>
					</li>
					<li>
						<a>Pricing</a>
					</li>
					<li>
						<a>Docs</a>
					</li>
					<li>
						<a>FAQ</a>
					</li>
					<li>
						<a
							href={githubUrl}
							target="_blank"
							className="flex items-center md:text-main"
						>
							<span className="inline-block">
								<AiFillStar />
							</span>
							&nbsp; us on GitHub
						</a>
					</li>
					<li>
						<button
							onClick={toggleOpen}
							className="absolute bottom-2 left-1/2 -translate-x-1/2 md:hidden"
						>
							<BsChevronCompactUp className="text-main" />
						</button>
					</li>
				</ul>
			</div>
		</nav>
	);
}

function useMenu() {
	const [open, setOpen] = useState<boolean>(false);
	const toggleOpen = () => setOpen((o) => !o);
	return { open, toggleOpen };
}

// web/src/routes/index/components/nav.svelte
<script lang="ts">
	import cx from "classnames";
	import Logo from "@assets/logo.svg";
	import StarUs from "./star.svelte";
	import LogInBtn from "./login.svelte";
	import Hamburger from "../assets/hamburger.svelte";

	export let loading: boolean;

	let show: boolean = false;
	const toggleOpen: () => void = () => (show = !show);
</script>

<nav
	class={cx([
		"sticky left-0 top-0 z-[49] transition-all translate-y-0",
		"bg-dark justify-between bg-dark-200/60 backdrop-blur md:flex",
	])}
>
	<div class="flex h-16 items-center justify-between px-5">
		<img src={Logo} alt="logo" />
		<button
			on:click={toggleOpen}
			class="rounded-md bg-inherit p-2 transition-all hover:bg-[#3a3a3a] md:hidden"
		>
			<Hamburger />
		</button>
	</div>

	<div class="absolute left-0 top-16 w-full pr-4 md:static md:w-max">
		<ul
			class={cx([
				`w-full h-0 py-0`,
				{ "h-[350px] py-5": show },
				"text-light bg-[#1e1e1e] font-semibold",
				"flex flex-col items-center justify-between",
				"transition-all",
				"relative overflow-clip",
				"z-50 gap-10 md:h-full md:flex-row md:bg-inherit",
			])}
		>
			<li>
				<LogInBtn {loading} />
			</li>
			<li>
				<a href="/pricing">Pricing</a>
			</li>
			<li>
				<a href="/docs">Docs</a>
			</li>
			<li>
				<a href="/faq">FAQ</a>
			</li>
			<li>
				<StarUs />
			</li>
		</ul>
	</div>
</nav>
